app/Http/routes.php
<?php

Route::controller('auth/password', 'Auth\PasswordController', [
   'getEmail'  => 'auth.password.email',
   'getReset'  => 'auth.password.reset'
]);

Route::controller('auth', 'Auth\AuthController', [
   'getLogin'  => 'auth.login',
   'getLogout' => 'auth.logout'
]);

Route::get('admin/users/{users}/confirm', [
    'as' => 'admin.users.confirm',
    'uses' => 'Admin\UsersController@confirm'
]);
Route::resource('admin/users', 'Admin\UsersController', ['except' => ['show']]);

Route::get('admin/pages/{pages}/confirm', [
    'as' => 'admin.pages.confirm',
    'uses' => 'Admin\PagesController@confirm'
]);
Route::resource('admin/pages', 'Admin\PagesController', ['except' => ['show']]);

Route::get('admin/blog/{blog}/confirm', [
    'as' => 'admin.blog.confirm',
    'uses' => 'Admin\BlogController@confirm'
]);
Route::resource('admin/blog', 'Admin\BlogController');

Route::get('admin/dashboard', ['as' => 'admin.dashboard', 'uses' => 'Admin\DashboardController@index']);

Route::get('/', ['middleware' => 'auth' ,function () {
    return view('welcome');
}]);

app/User.php
<?php

namespace SundaySim;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password'];

    protected $dates = ['last_login_at'];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];

    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace SundaySim\Http\Controllers\Admin;

use SundaySim\User;
use Illuminate\Http\Request;
use SundaySim\Http\Requests;

class UsersController extends Controller
{
    protected $users;

    public function __construct(User $users)
    {
        $this->users = $users;

        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->users->paginate(10);

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(User $user)
    {
        return view('admin.users.form', compact('user'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StoredUserRequest $request)
    {
        $this->users->create($request->only('name', 'email', 'password'));

        return redirect(route('admin.users.index'))->with('status', 'User has been created.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->users->findOrFail($id);

        return view('admin.users.form', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\UpdateUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        $user->fill($request->only('name', 'email', 'password'))->save();

        return redirect(route('admin.users.edit', $user->id))->with('status', 'User has been updated.');
    }

    public function confirm(Requests\DeleteUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        return view('admin.users.confirm', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Requests\DeleteUserRequest $request, $id)
    {
        $user = $this->users->findOrFail($id);

        $user->delete();

        return redirect(route('admin.users.index'))->with('status', 'User has been deleted.');
    }
}

resources/views/admin/users/confirm.blade.php
@extends('layouts.admin')

@section('title', 'Deleting ' . $user->name)

@section('content')
    {!! Form::open(['method' => 'delete', 'route' => ['admin.users.destroy', $user->id]]) !!}
        <div class="alert alert-danger">
            <strong>Warning!</strong> You are about to delete a user. This action can not be undone.
             Are you sure you want to continue?
        </div>
        {!! Form::submit('Yes, delete this user', ['class' => 'btn btn-danger']) !!}
        <a href="{{ route('admin.users.index') }}" class="btn btn-success">
            <strong>No, get me out here.</strong>
        </a>
    {!! Form::close() !!}
@endsection

resources/views/admin/users/form.blade.php
@extends('layouts.admin')

@section('title', $user->exists ? 'Editing ' . $user->name : 'Create New User')

@section('content')
    {!! Form::model($user, [
            'method' => $user->exists ? 'put' : 'post',
            'route'  => $user->exists ? ['admin.users.update', $user->id] : ['admin.users.store']
    ]) !!}

    <div class="form-group">
        {!! Form::label('name') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('email') !!}
        {!! Form::text('email', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('password') !!}
        {!! Form::password('password', ['class' => 'form-control']) !!}
    </div>

    <div class="form-group">
        {!! Form::label('password_confirmation') !!}
        {!! Form::password('password_confirmation', ['class' => 'form-control']) !!}
    </div>

    {!! Form::submit($user->exists ? 'Save User' : 'Create New User', ['class' => 'btn btn-primary'])!!}

    {!! Form::close() !!}
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('title', 'Users')

@section('content')
    <a href="{{ route('admin.users.create') }}"><button class="btn btn-primary">Create New User</button></a>
    <table class="table table-hover ">
    	<thead>
    		<tr>
    			<th>Name</th>
    			<th>E-mail</th>
    			<th>Edit</th>
    			<th>Delete</th>
    		</tr>
    	</thead>
    <tbody>
        @foreach($users as $user)
            <tr>
                <td>
                    <a href="{{ route('admin.users.edit', $user->id) }}">{{ $user->name }}</a>
                </td>
                <td>{{ $user->email }}</td>
                <td>
                    <a href="{{ route('admin.users.edit', $user->id) }}">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                </td>
                <td>
                    <a href="{{ route('admin.users.confirm', $user->id) }}">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>
        @endforeach
    </tbody>
    </table>
    {!! $users->render() !!}
@endsection