app/Http/routes.php
<?php

Route::controller('auth/password', 'Auth\PasswordController', [
   'getEmail'  => 'auth.password.email',
   'getReset'  => 'auth.password.reset'
]);

Route::controller('auth', 'Auth\AuthController', [
   'getLogin'  => 'auth.login',
   'getLogout' => 'auth.logout'
]);

Route::get('admin/users/{users}/confirm', [
    'as' => 'admin.users.confirm',
    'uses' => 'Admin\UsersController@confirm'
]);
Route::resource('admin/users', 'Admin\UsersController', ['except' => ['show']]);

Route::get('admin/pages/{pages}/confirm', [
    'as' => 'admin.pages.confirm',
    'uses' => 'Admin\PagesController@confirm'
]);
Route::resource('admin/pages', 'Admin\PagesController', ['except' => ['show']]);

Route::get('admin/blog/{blog}/confirm', [
    'as' => 'admin.blog.confirm',
    'uses' => 'Admin\BlogController@confirm'
]);
Route::resource('admin/blog', 'Admin\BlogController');

Route::get('admin/dashboard', ['as' => 'admin.dashboard', 'uses' => 'Admin\DashboardController@index']);

Route::get('/', ['middleware' => 'auth' ,function () {
    return view('welcome');
}]);

resources/views/admin/pages/confirm.blade.php
@extends('layouts.admin')

@section('title', 'Deleting ' . $page->title)

@section('content')
    {!! Form::open(['method' => 'delete', 'route' => ['admin.pages.destroy', $page->id]]) !!}
        <div class="alert alert-danger">
            <strong>Warning!</strong> You are about to delete a page. This action can not be undone.
             Are you sure you want to continue?
        </div>
        {!! Form::submit('Yes, delete this page', ['class' => 'btn btn-danger']) !!}
        <a href="{{ route('admin.pages.index') }}" class="btn btn-success">
            <strong>No, get me out here.</strong>
        </a>
    {!! Form::close() !!}
@endsection

resources/views/admin/pages/form.blade.php
@extends('layouts.admin')

@section('title', $page->exists ? 'Editing '.$page->title : 'Create New Page')

@section('content')
{!! Form::model($page, [
    'method' => $page->exists ? 'put' : 'post',
    'route'  => $page->exists ? ['admin.pages.update', $page->id] : ['admin.pages.store']
]) !!}

<div class="form-group">
    {!! Form::label('title') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('uri', 'URI') !!}
    {!! Form::text('uri', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('name') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}

    <p class="help-block">
        This name is used to generate links to the page.
    </p>
</div>

<div class="form-group row">
    <div class="col-md-12">
        {!! Form::label('template') !!}
    </div>
    <div class="col-md-4">
        {!! Form::select('template', $templates, null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group row">
    <div class="col-md-12">
        {!! Form::label('order') !!}
    </div>
    <div class="col-md-2">
        {!! Form::select('order', [
            ''        => '',
            'before'  => 'Before',
            'after'   => 'After',
            'childOf' => 'Child Of'
        ], null, ['class' => 'form-control']) !!}
    </div>
    <div class="col-md-5">
        {!! Form::select('orderPage', [
                '' => ''
            ] + $orderPages->lists('padded_title', 'id')->toArray(), null, ['class' => 'form-control']) 
        !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('content') !!}
    {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
</div>

{!! Form::submit($page->exists ? 'Save Page' : 'Create New Page', ['class' => 'btn btn-primary'])!!}

{!! Form::close() !!}

<script>
    new SimpleMDE().render();
</script>

@endsection

resources/views/admin/pages/index.blade.php
@extends('layouts.admin')

@section('title', 'Pages')

@section('content')
    <a href="{{ route('admin.pages.create') }}" class="btn btn-primary">Create New Page</a>
    <table class="table table-hover">
        <thead>
            <tr>
                <td>Title</td>
                <td>URI</td>
                <td>Name</td>
                <td>Template</td>
                <td>Edit</td>
                <td>Delete</td>
            </tr>
        </thead>
        <tbody>
            @if($pages->isEmpty())
                <tr>
                    <td colspan="5" align="center">There are no pages.</td>
                </tr>
            @else
                @foreach($pages as $page)
                    <tr>
                        <td>
                            {!! $page->linkToPaddedTitle(route('admin.pages.edit', $page->id)) !!}
                        </td>
                        <td><a href="{{ url($page->uri) }}">{{ $page->pretty_uri }}</a></td>
                        <td>{{ $page->name or '...'}}</td>
                        <td>{{ $page->template or '...'}}</td>
                        <td>
                            <a href="{{ route('admin.pages.edit', $page->id) }}">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                        </td>
                        <td>
                            <a href="{{ route('admin.pages.confirm', $page->id) }}">
                                <span class="glyphicon glyphicon-remove"></span>
                            </a>
                        </td>
                    </tr>
                @endforeach
            @endif
        </tbody>
    </table>
@endsection