app/Http/routes.php
<?php

Route::controller('auth/password', 'Auth\PasswordController', [
   'getEmail'  => 'auth.password.email',
   'getReset'  => 'auth.password.reset'
]);

Route::controller('auth', 'Auth\AuthController', [
   'getLogin'  => 'auth.login',
   'getLogout' => 'auth.logout'
]);

Route::get('admin/users/{users}/confirm', [
    'as' => 'admin.users.confirm',
    'uses' => 'Admin\UsersController@confirm'
]);
Route::resource('admin/users', 'Admin\UsersController', ['except' => ['show']]);

Route::get('admin/pages/{pages}/confirm', [
    'as' => 'admin.pages.confirm',
    'uses' => 'Admin\PagesController@confirm'
]);
Route::resource('admin/pages', 'Admin\PagesController', ['except' => ['show']]);

Route::get('admin/blog/{blog}/confirm', [
    'as' => 'admin.blog.confirm',
    'uses' => 'Admin\BlogController@confirm'
]);
Route::resource('admin/blog', 'Admin\BlogController');

Route::get('admin/dashboard', ['as' => 'admin.dashboard', 'uses' => 'Admin\DashboardController@index']);

Route::get('/', ['middleware' => 'auth' ,function () {
    return view('welcome');
}]);

app/Http/Controllers/Admin/BlogController.php
<?php

namespace SundaySim\Http\Controllers\Admin;

use SundaySim\Post;
use Illuminate\Http\Request;
use SundaySim\Http\Requests;

class BlogController extends Controller
{
    protected $posts;

    public function __construct(Post $posts)
    {
        $this->posts = $posts;

        parent::__construct();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = $this->posts->orderBy('published_at', 'desc')->paginate(10);

        return view('admin.blog.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $post)
    {
        return view('admin.blog.form', compact('post'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\StorePostRequest $request)
    {
        $this->posts->create([
            'author_id' => auth()->user()->id] +
            $request->only('title', 'slug', 'published_at', 'excerpt', 'body')
        );

        return redirect(route('admin.blog.index'))->with('status', 'Post has been created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = $this->posts->findOrFail($id);

        return view('admin.blog.form', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\UpdatePostRequest $request, $id)
    {
        $post = $this->posts->findOrFail($id);

        $post->fill($request->only(
            'title', 'slug', 'published_at', 'excerpt', 'body'
        ))->save();

        return redirect(route('admin.blog.index'))->with('status', 'Post has been updated.');
    }


    /**
     * Confirm the removal the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function confirm($id)
    {
        $post = $this->posts->findOrFail($id);

        return view('admin.blog.confirm', compact('post'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = $this->posts->findOrFail($id);

        $post->delete();

        return redirect(route('admin.blog.index'))->with('status', 'Post has been deleted.');
    }
}

resources/views/admin/blog/confirm.blade.php
@extends('layouts.admin')

@section('title', 'Deleting ' . $post->title)

@section('content')
    {!! Form::open(['method' => 'delete', 'route' => ['admin.blog.destroy', $post->id]]) !!}
        <div class="alert alert-danger">
            <strong>Warning!</strong> You are about to delete a post. This action can not be undone.
             Are you sure you want to continue?
        </div>
        {!! Form::submit('Yes, delete this post', ['class' => 'btn btn-danger']) !!}
        <a href="{{ route('admin.pages.index') }}" class="btn btn-success">
            <strong>No, get me out here.</strong>
        </a>
    {!! Form::close() !!}
@endsection

resources/views/admin/blog/form.blade.php
@extends('layouts.admin')

@section('title', $post->exists ? 'Editing '.$post->title : 'Create New Blog Post')

@section('content')

{!! Form::model($post, [
    'method' => $post->exists ? 'put' : 'post',
    'route'  => $post->exists ? ['admin.blog.update', $post->id] : ['admin.blog.store']
]) !!}

<div class="form-group">
    {!! Form::label('title') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('slug') !!}
    {!! Form::text('slug', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group row">
    <div class="col-md-12">
        {!! Form::label('published_at') !!}
    </div>
    <div class="col-md-4">
        {!! Form::text('published_at', null, ['class' => 'form-control']) !!}
    </div>
</div>

<div class="form-group">
    {!! Form::label('excerpt') !!}
    {!! Form::textarea('excerpt', null, ['class' => 'form-control', 'rows' => '5']) !!}
</div>

<div class="form-group">
    {!! Form::label('body') !!}
    {!! Form::textarea('body', null, ['class' => 'form-control', 'id' => 'editor']) !!}
</div>

{!! Form::submit($post->exists ? 'Save Post' : 'Create New Post', ['class' => 'btn btn-primary'])!!}

{!! Form::close() !!}

<script>
    $('[name=published_at]').datetimepicker({
        allowInputToggle: true,
        format: 'YYYY-MM-DD HH:mm:ss',
        showClear: true,
        defaultDate: '{{ old('published_at', $post->published_at) }}'
    });

    $('[name=title]').on('blur', function() {
        var slugElement = $('[name=slug]');

        if (slugElement.val()) {
            return;
        }

        slugElement.val(
            this.value.toLowerCase()
            .replace(/[^a-z0-9-]+/g, '-')
            .replace(/^-+|-+$/g, '')
        );
    });


     var editor_config = {
        path_absolute : "{{ URL::to('/') }}/",
        selector: '#editor',
        language: 'pt_BR',
        height: 500,
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor colorpicker textpattern imagetools"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
        relative_urls: false,
        file_browser_callback : function(field_name, url, type, win) {
            var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
            var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;
            var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
            if (type == 'image') {
                cmsURL = cmsURL + "&type=Images";
            } else {
                cmsURL = cmsURL + "&type=Files";
            }
            tinyMCE.activeEditor.windowManager.open({
                file : cmsURL,
                title : 'Filemanager',
                width : x * 0.8,
                height : y * 0.8,
                resizable : "yes",
                close_previous : "no"
            });
        }
    };
    tinymce.init(editor_config);
</script>

@endsection

resources/views/admin/blog/index.blade.php
@extends('layouts.admin')

@section('title', 'Blog Posts')

@section('content')
    <a href="{{ route('admin.blog.create') }}"><button class="btn btn-primary">Create New Post</button></a>
    <table class="table table-hover ">
    	<thead>
    		<tr>
    			<th>Title</th>
    			<th>Slug</th>
    			<th>Author</th>
    			<th>Published</th>
    			<th>Edit</th>
    			<th>Delete</th>
    		</tr>
    	</thead>
    <tbody>
        @foreach($posts as $post)
            <tr class="{{ $post->published_highlight }}">
                <td>
                    <a href="{{ route('admin.blog.edit', $post->id) }}">{{ $post->title  }}</a>
                </td>
                <td>{{ $post->slug }}</td>
                <td>{{ $post->author->name }}</td>
                <td>{{ $post->published_date }}</td>
                <td>
                    <a href="{{ route('admin.blog.edit', $post->id) }}">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                </td>
                <td>
                    <a href="{{ route('admin.blog.confirm', $post->id) }}">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>
        @endforeach
    </tbody>
    </table>
    {!! $posts->render() !!}
@endsection